### ISSUE TITLE
BetterShardsBungee needs the same plugin name

### ISSUE THREAD

**Issue by erocs** [Civcraft/BetterShards#105]
Currently BetterShardsBukkit and BetterShardsBungee share the same plugin name. That leads to the problem where the Bukkit jar is placed in a bungeecord's plugins directory and other plugins "depends: [BetterShards]" allows the other plugins to load even though BetterShardsBungee doesn't exist.

Rename the BetterShardsBungee plugin name to BetterShardsBungee.

**Comment by ProgrammerDan** [comment]
So the issue here isn't the naming of the plugins. 

On build, the plugins _are very clearly labelled_. 

BetterShardsBukkit.jar

and

BetterShardsBungee.jar

No issues are to be found there.

The issue is simply how the deploy mechanism is constructed demands that we strip all version and identifying information from the jars, and rename it to match the plugin name.

That's the source of the problem, IMHO.

**Comment by Maxopoly** [comment]
I think the plugin names are fine, the issue is the deploy thing.
